# Generated by Django 4.2.13 on 2024-07-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(related_name='users', to='main.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='team', to='main.user'),
        ),
    ]
