# Generated by Django 4.2.13 on 2024-07-13 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_last_login_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='discussions',
            field=models.ManyToManyField(related_name='dicussion', to='main.discussion'),
        ),
        migrations.AddField(
            model_name='project',
            name='pseudo_team',
            field=models.ManyToManyField(related_name='pseudo_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='assingment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default=1, upload_to=main.models.user_profile_path),
            preserve_default=False,
        ),
    ]
