# Generated by Django 4.2.13 on 2024-07-15 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_submission_project_project_discussions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('linkedin_url', models.URLField()),
                ('github_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ColabProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=255)),
                ('img', models.ImageField(default='profiles/default.jpg', upload_to='profiles/')),
                ('location', models.CharField(max_length=255)),
                ('times', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Free Lancer', 'Free Lancer')], max_length=50)),
                ('wages', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
