# Generated by Django 4.2.13 on 2024-07-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_homestatistic_hometeammember_hometestimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
